name: Automatic Approve for PR Workflows
on:
  pull_request_target:
    types: [opened]

jobs:
  automatic-approve:
    name: Automatic Approve
    runs-on: ubuntu-latest
    steps:
      - name: Approve PR Workflow
        uses: hmarr/auto-approve-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
