name: Auto Approve Workflow
on:
  pull_request_target:
    types: [opened, synchronize]

jobs:
  approve-workflow:
    runs-on: ubuntu-latest
    permissions:
      actions: write  # ✅ Needed to approve workflows
    steps:
      - name: Approve Workflow
        run: |
          gh api repos/${{ github.repository }}/actions/runs \
            --method GET \
            --header "Authorization: token ${{ secrets.PAT }}" \
            --jq '.workflow_runs[] | select(.status=="waiting") | .id' | \
          while read run_id; do
            gh api repos/${{ github.repository }}/actions/runs/$run_id/approve \
              --method POST \
              --header "Authorization: token ${{ secrets.PAT }}"
          done
        env:
          GH_TOKEN: ${{ secrets.PAT }}
