name: Automatic Workflow Approval
on:
  workflow_run:
    workflows: ["github-actions-demo.yml"]  # Change this to your workflow filename
    types:
      - requested

jobs:
  approve-workflow:
    name: Approve Workflow Run
    runs-on: ubuntu-latest
    steps:
      - name: Approve Workflow
        uses: hmarr/auto-approve-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }
