name: Automatic Workflow Approval
on:
  workflow_run:
    workflows: ["github-actions-demo.yml"]  # Change this to your actual workflow file
    types:
      - requested

jobs:
  approve-workflow:
    name: Approve Workflow Run
    runs-on: ubuntu-latest
    permissions:
      actions: write  # Needed to approve workflows
    steps:
      - name: Approve Workflow
        uses: actions/approve-workflow-runs@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
